"""
Abstract repository interfaces.
All database operations go through these interfaces,
so the app doesn't care if the backend is SQLite or MongoDB.
"""

from abc import ABC, abstractmethod
from datetime import datetime

# Delete-method contract (applies across every repo in this module):
#   * `delete(id)` for a single row → bool (True if row existed and was removed).
#   * `delete_many(ids)` / `delete_by_*` bulk deletes → int (rows removed).
# Update-method contract:
#   * `update(id, data)` → returns the updated dict, or None if not found.
#   * The router layer is responsible for stripping None/"unchanged" fields
#     (e.g. `model_dump(exclude_none=True)`) before calling — repo implementations
#     still defensively skip None on user-facing `Site` and `Tool` updates so
#     partial-update PATCHes don't wipe existing columns.


class BaseSiteRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, site_id: str) -> dict | None: ...
    @abstractmethod
    async def get_by_token(self, token: str) -> dict | None: ...
    @abstractmethod
    async def list_all(self) -> list[dict]: ...
    @abstractmethod
    async def update(self, site_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete(self, site_id: str) -> bool: ...

    async def get_crawl_password(self, site_id: str) -> str | None:
        """Get the raw (unmasked) crawl login password. Override in implementations."""
        return None


class BaseKnowledgeRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, chunk_id: str) -> dict | None: ...
    @abstractmethod
    async def list_by_site(self, site_id: str, page: int = 1, per_page: int = 20, search: str | None = None) -> dict: ...
    @abstractmethod
    async def update(self, chunk_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete(self, chunk_id: str) -> bool: ...
    @abstractmethod
    async def create_many(self, chunks: list[dict]) -> list[str]: ...
    @abstractmethod
    async def delete_many(self, chunk_ids: list[str]) -> int: ...
    @abstractmethod
    async def get_many(self, chunk_ids: list[str]) -> list[dict]: ...
    @abstractmethod
    async def list_crawled_urls(self, site_id: str) -> list[dict]: ...
    @abstractmethod
    async def list_content_hashes(self, site_id: str) -> set[str]: ...
    @abstractmethod
    async def list_by_url(self, site_id: str, source_url: str) -> list[dict]: ...
    @abstractmethod
    async def delete_by_url(self, site_id: str, source_url: str) -> int: ...
    @abstractmethod
    async def delete_all_by_site(self, site_id: str) -> int: ...


class BaseToolRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, tool_id: str) -> dict | None: ...
    @abstractmethod
    async def list_by_site(self, site_id: str) -> list[dict]: ...
    @abstractmethod
    async def list_enabled_by_site(self, site_id: str) -> list[dict]: ...
    @abstractmethod
    async def update(self, tool_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete(self, tool_id: str) -> bool: ...


class BaseChatSessionRepo(ABC):
    """Chat-session repository contract.

    Return-value rules (both SQLite and MongoDB implementations MUST agree):
      - update_messages / set_ended / add_token_usage: `True` iff the session
        EXISTS (regardless of whether the stored value actually changed).
        Mongo implementations must use `matched_count`, not `modified_count`.
      - create: returns the newly-persisted dict with ISO-string datetimes.
      - get_by_id / list_*: serialized dicts with ISO-string datetimes.
    """

    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, session_id: str) -> dict | None: ...
    @abstractmethod
    async def list_by_site(self, site_id: str, page: int = 1, per_page: int = 20) -> list[dict]: ...
    @abstractmethod
    async def list_by_site_since(self, site_id: str, since: datetime) -> list[dict]: ...
    @abstractmethod
    async def update_messages(self, session_id: str, messages: list[dict]) -> bool: ...
    @abstractmethod
    async def set_ended(self, session_id: str, clear: bool = False) -> bool: ...
    @abstractmethod
    async def aggregate_overview(self, site_id: str, since: datetime) -> dict:
        """Return {"total_sessions", "total_messages", "avg_session_duration_seconds"}
        aggregated at the DB layer (no per-session Python iteration)."""
        ...
    @abstractmethod
    async def add_token_usage(
        self, session_id: str, in_tokens: int, out_tokens: int, cost_usd: float
    ) -> bool:
        """Atomically increment tokens_input, tokens_output, and cost_usd on a session.
        Returns True iff the session exists (matched), mirroring update_messages."""
        ...


class BaseCrawlJobRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, job_id: str) -> dict | None: ...
    @abstractmethod
    async def list_by_site(self, site_id: str) -> list[dict]: ...
    @abstractmethod
    async def update(self, job_id: str, data: dict) -> bool: ...


class BaseVisitorMemoryRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict:
        ...

    @abstractmethod
    async def get_by_id(self, memory_id: str) -> dict | None:
        ...

    @abstractmethod
    async def list_by_visitor(self, visitor_id: str, site_id: str) -> list[dict]:
        ...

    @abstractmethod
    async def upsert(self, visitor_id: str, site_id: str, key: str, data: dict) -> dict:
        ...

    @abstractmethod
    async def delete(self, memory_id: str) -> bool:
        ...

    @abstractmethod
    async def delete_by_visitor(self, visitor_id: str, site_id: str) -> int:
        ...

    @abstractmethod
    async def list_by_site(self, site_id: str) -> list[dict]:
        ...


class BaseConversationSummaryRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict:
        ...

    @abstractmethod
    async def get_by_session(self, session_id: str) -> dict | None:
        ...

    @abstractmethod
    async def upsert_by_session(self, session_id: str, data: dict) -> dict:
        ...

    @abstractmethod
    async def delete(self, summary_id: str) -> bool:
        ...


class BaseUserRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, user_id: str) -> dict | None: ...
    @abstractmethod
    async def get_by_username(self, username: str) -> dict | None: ...
    @abstractmethod
    async def count(self) -> int: ...
    @abstractmethod
    async def list_all(self) -> list[dict]: ...
    @abstractmethod
    async def update_role(self, user_id: str, role: str) -> dict | None: ...
    @abstractmethod
    async def delete(self, user_id: str) -> bool: ...


class BaseAuditLogRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def list_by_site(self, page: int = 1, per_page: int = 50) -> dict: ...


class BaseLLMKeyRepo(ABC):
    @abstractmethod
    async def list_all(self) -> list[dict]: ...
    @abstractmethod
    async def get_by_provider(self, provider: str) -> dict | None: ...
    @abstractmethod
    async def upsert(self, provider: str, data: dict) -> dict: ...
    @abstractmethod
    async def delete_by_provider(self, provider: str) -> bool: ...


class BaseFlowRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, flow_id: str) -> dict | None: ...
    @abstractmethod
    async def list_by_site(self, site_id: str) -> list[dict]: ...
    @abstractmethod
    async def update(self, flow_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete(self, flow_id: str) -> bool: ...
    @abstractmethod
    async def delete_by_site(self, site_id: str) -> int: ...


class BaseFlowStepRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, step_id: str) -> dict | None: ...
    @abstractmethod
    async def list_by_flow(self, flow_id: str) -> list[dict]: ...
    @abstractmethod
    async def update(self, step_id: str, data: dict) -> dict | None: ...
    @abstractmethod
    async def delete(self, step_id: str) -> bool: ...
    @abstractmethod
    async def delete_by_flow(self, flow_id: str) -> int: ...
    @abstractmethod
    async def reorder(self, flow_id: str, step_ids: list[str]) -> bool: ...
