"""
Abstract repository interfaces.
All database operations go through these interfaces,
so the app doesn't care if the backend is SQLite or MongoDB.
"""

from abc import ABC, abstractmethod
from typing import Optional


class BaseSiteRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, site_id: str) -> Optional[dict]: ...
    @abstractmethod
    async def get_by_token(self, token: str) -> Optional[dict]: ...
    @abstractmethod
    async def list_all(self) -> list[dict]: ...
    @abstractmethod
    async def update(self, site_id: str, data: dict) -> Optional[dict]: ...
    @abstractmethod
    async def delete(self, site_id: str) -> bool: ...


class BaseKnowledgeRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, chunk_id: str) -> Optional[dict]: ...
    @abstractmethod
    async def list_by_site(self, site_id: str, page: int = 1, per_page: int = 20, search: Optional[str] = None) -> dict: ...
    @abstractmethod
    async def update(self, chunk_id: str, data: dict) -> Optional[dict]: ...
    @abstractmethod
    async def delete(self, chunk_id: str) -> bool: ...
    @abstractmethod
    async def create_many(self, chunks: list[dict]) -> list[str]: ...


class BaseToolRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, tool_id: str) -> Optional[dict]: ...
    @abstractmethod
    async def list_by_site(self, site_id: str) -> list[dict]: ...
    @abstractmethod
    async def list_enabled_by_site(self, site_id: str) -> list[dict]: ...
    @abstractmethod
    async def update(self, tool_id: str, data: dict) -> Optional[dict]: ...
    @abstractmethod
    async def delete(self, tool_id: str) -> bool: ...


class BaseChatSessionRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, session_id: str) -> Optional[dict]: ...
    @abstractmethod
    async def list_by_site(self, site_id: str, page: int = 1, per_page: int = 20) -> list[dict]: ...
    @abstractmethod
    async def update_messages(self, session_id: str, messages: list[dict]) -> bool: ...
    @abstractmethod
    async def set_ended(self, session_id: str) -> bool: ...


class BaseCrawlJobRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, job_id: str) -> Optional[dict]: ...
    @abstractmethod
    async def list_by_site(self, site_id: str) -> list[dict]: ...
    @abstractmethod
    async def update(self, job_id: str, data: dict) -> bool: ...


class BaseUserRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def get_by_id(self, user_id: str) -> Optional[dict]: ...
    @abstractmethod
    async def get_by_username(self, username: str) -> Optional[dict]: ...
    @abstractmethod
    async def count(self) -> int: ...
    @abstractmethod
    async def list_all(self) -> list[dict]: ...
    @abstractmethod
    async def update_role(self, user_id: str, role: str) -> Optional[dict]: ...
    @abstractmethod
    async def delete(self, user_id: str) -> bool: ...


class BaseVisitorMemoryRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict:
        ...

    @abstractmethod
    async def get_by_id(self, memory_id: str) -> Optional[dict]:
        ...

    @abstractmethod
    async def list_by_visitor(self, visitor_id: str, site_id: str) -> list[dict]:
        ...

    @abstractmethod
    async def upsert(self, visitor_id: str, site_id: str, key: str, data: dict) -> dict:
        ...

    @abstractmethod
    async def delete(self, memory_id: str) -> bool:
        ...

    @abstractmethod
    async def delete_by_visitor(self, visitor_id: str, site_id: str) -> int:
        ...


class BaseConversationSummaryRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict:
        ...

    @abstractmethod
    async def get_by_session(self, session_id: str) -> Optional[dict]:
        ...

    @abstractmethod
    async def upsert_by_session(self, session_id: str, data: dict) -> dict:
        ...

    @abstractmethod
    async def delete(self, summary_id: str) -> bool:
        ...


class BaseAuditLogRepo(ABC):
    @abstractmethod
    async def create(self, data: dict) -> dict: ...
    @abstractmethod
    async def list_by_site(self, page: int = 1, per_page: int = 50) -> dict: ...
